name: Test and build

on:
  push:
    branches-ignore:
      - master

env:
  CI: true
jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node: [18, 20]
    steps:
      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v3
#        name: Setup node ${{ matrix.node }}
#        with:
#          node-version: ${{ matrix.node }}
#          cache: 'npm'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.13
      - name: Install dependencies
        run: bun install --frozen-lockfile
#      - name: Test
#        run: npm run test
      - name: Build
        run: bun run build
# TODO setup tests
#      - name: Report coverage
#        if: ${{ matrix.node == '18' }}
#        uses: codecov/codecov-action@v3